name: trial-mysql

volumes:
  mysql_data:

networks:
  frontend:
  backend:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - ${PORT-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  adminer:
    container_name: adminer-for-mysql
    image: adminer
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - ${PORT_UI-8080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_DB: mysql
      ADMINER_DESIGN: dracula
      # Dev ONLY
      # ADMINER_SINGLE_USER: "true"
      # ADMINER_USERNAME: ${POSTGRES_USER:-root}
      # ADMINER_PASSWORD: ${POSTGRES_PASSWORD}
