version: "3.9"

services:
  db:
    image: mysql
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  ui:
    image: adminer
    depends_on:
      - db
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080

volumes:
  mysql_data:

networks:
  frontend:
  backend:
