version: "3.9"

volumes:
  mysql_data:

networks:
  frontend:
  backend:

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - mysql
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080
